# Generated by Django 6.0.5 on 2026-05-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RideLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_id', models.CharField(db_index=True, max_length=128)),
                ('passenger_uid', models.CharField(blank=True, max_length=128)),
                ('driver_uid', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('otp_sent', 'OTP Sent'), ('otp_verified', 'OTP Verified'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('fare', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pickup', models.CharField(blank=True, max_length=256)),
                ('drop', models.CharField(blank=True, max_length=256)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Ride Log',
                'verbose_name_plural': 'Ride Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RideOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('passenger_uid', models.CharField(blank=True, max_length=128)),
                ('driver_uid', models.CharField(blank=True, max_length=128)),
                ('otp', models.CharField(max_length=4)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Ride OTP',
                'verbose_name_plural': 'Ride OTPs',
                'ordering': ['-created_at'],
            },
        ),
    ]
